POST http://localhost:8081/v1/photo/1
Content-Type: application/json

{"url":"raccoon.com", "GCP":"image.png","Img":"image1.png"}

###

POST http://localhost:8081/v1/photo/2
Content-Type: application/json

{"url":"raccoon.com", "GCP":"image.png","Img":"image2.png"}

###

GET http://localhost:8081/v1/photo
Content-Type: application/json