POST http://localhost:8081/v1/images
Content-Type: application/json

{"url":"raccoon.com", "GCP":"image.png","Img":"image1.png"}

###

POST http://localhost:8081/v1/images
Content-Type: application/json

{"url":"raccoon.com", "GCP":"image.png","Img":"image232434.png"}

###

GET http://localhost:8081/v1/images
Content-Type: application/json