apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: showcase-backend
spec:
  rules:
    - accessStrategies:
        - config: {}
          handler: allow
      methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - HEAD
      path: /.*
  service:
    host: backend.{YOUR_CLUSTER_DOMAIN}
    name: showcase-backend-service
    port: 8081
  gateway: kyma-gateway.kyma-system.svc.cluster.local