apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: showcase-backend
spec:
  rules:
    - path: /.*
      methods: [ "GET", "POST"]
      accessStrategies:
        - handler: noop
  service:
    host: backend.{YOUR_CLUSTER_DOMAIN}
    name: showcase-backend-service
    port: 8081
  gateway: kyma-gateway.kyma-system.svc.cluster.local