apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: raccoonsteam/backend:0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: REDIS_URL
              value: "redis-leader.default:6379"
            - name: REDIS_PASSWORD
              value: ""
            - name: PORT
              value: "8081"
