kind: Service
apiVersion: v1
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    app: backend
  type: NodePort
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081