apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: showcase-frontend
spec:
  rules:
    - accessStrategies:
        - config: {}
          handler: allow
      methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - HEAD
      path: /.*
  service:
    host: frontend.{YOUR_CLUSTER_DOMAIN}
    name: showcase-frontend-service
    port: 80
  gateway: kyma-gateway.kyma-system.svc.cluster.local