apiVersion: apps/v1
kind: Deployment
metadata:
  name: showcase-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: showcase-frontend
  template:
    metadata:
      labels:
        app: showcase-frontend
    spec:
      volumes:
        - name: config
          configMap:
            name: showcase-frontend-config
            items:
              - key: config.json
                path: config.json
      containers:
        - name: showcase-frontend
          image: raccoonsteam/frontend:0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/app/config