apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: kaktusowy500/backend
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: REDIS_URL
              value: "hb-redis-micro-a65b2b40-cbbb-450d-aac2-42e2ec61846f-redis.grzyby:6379"
            - name: REDIS_PASSWORD
              value: "j8KgnRBUpk"
            - name: PORT
              value: "8081"

---
kind: Service
apiVersion: v1
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    app: backend
  type: NodePort
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081