apiVersion: serverless.kyma-project.io/v1alpha1
kind: Function
metadata:
  name: image-get
spec:
  deps: |-
    { 
      "name": "image-get",
      "version": "1.0.0",
      "dependencies": {
        "node-fetch": "2.6.1"
      }
    }
  env:
    - name: API_CONFIG
      valueFrom:
        configMapKeyRef:
          key: config.json
          name: showcase-frontend-config
  runtime: nodejs14
  source: |
    module.exports = { 
      main: async function (event, context) {
        const fetch = require('node-fetch');
        async function getBase64() {
          const URL = JSON.parse(process.env.API_CONFIG).API_URL + '/' + event.data;
          const response = await fetch(URL);
          const data = await response.json();
          return data;
        }
        try{
        const content = (await getBase64()).content;
        const base64 = content.replace(/data:.*?base64,/, '')
        console.log(base64);
        return base64;
        }catch(err){
          console.error(err);
          return null;
        }
      }
    }






