apiVersion: serverless.kyma-project.io/v1alpha1
kind: Function
metadata:
  name: image-put
spec:
  deps: |-
    { 
      "name": "image-put",
      "version": "1.0.0",
      "dependencies": {
        "node-fetch": "2.6.1"
      }
    }
  env:
    - name: API_CONFIG
      valueFrom:
        configMapKeyRef:
          key: config.json
          name: showcase-frontend-config
  runtime: nodejs14
  source: |
    module.exports = { 
      main: function (event, context) {
        const labels = { labels:[
          "chleb", "bulki"
          ]};
        const fetch = require('node-fetch');
        const putImageToApi = async (id, labels) => {
          const URL = JSON.parse(process.env.API_CONFIG).API_URL;
          const response = await fetch(URL,{
            method:'PUT',
            body: JSON.stringify({
              id: id,
              gcp: labels,
            }),
            headers: {
              'Content-type': 'application/json',
            },
          });
          return response.json();
        }
        try{
          putImageToApi(event.data, labels.labels);
        }catch(err){
          console.log(err);
        }
        
      }
    }
