apiVersion: serverless.kyma-project.io/v1alpha1
kind: Function
metadata:
  name: labels-text
spec:
  deps: |-
    { 
      "name": "labels-text",
      "version": "1.0.0",
      "dependencies": {
        "node-fetch": "2.6.1",
        "@google-cloud/vision":"2.3.8",
        "axios": "0.21.1",
        "nanoid": "3.1.25"
      }
    }
  env:
    - name: GCP_EMAIL
      valueFrom:
        secretKeyRef:
          key: GCP_EMAIL
          name: kyma-showcase-secret
    - name: GCP_API_KEY
      valueFrom:
        secretKeyRef:
          key: GCP_API_KEY
          name: kyma-showcase-secret
    - name: API_CONFIG
      valueFrom:
        configMapKeyRef:
          key: config.json
          name: showcase-functions-config
  runtime: nodejs14
  source: |-
    module.exports = {
      main: async function (event, context) {
        async function getBase64(id) {
          console.log("Getting base64 from DB");
          const fetch = require('node-fetch');
          const URL = JSON.parse(process.env.API_CONFIG).API_URL + '/' + id;
          const response = await fetch(URL);
          const data = await response.json();
          const content = data.content;
          const base64 = content.replace(/data:.*?base64,/, '');
          console.log("Base64 loaded");
          return base64;
        }

        async function getFontDetails(base64){
          console.log("Getting font details from GCP");
          const vision = require('@google-cloud/vision');
          const options = {
            credentials: {
              client_email: process.env.GCP_EMAIL,
              private_key: process.env.GCP_API_KEY.replace(/\\n/gm, '\n'),
            },
          };

          const client = new vision.ImageAnnotatorClient(options);
          const request = {
            image: {
              content: Buffer.from(base64, 'base64'),
            },
          };

          const [result] = await client.textDetection(request);
          const resultTexts = result.textAnnotations;
          const fontDetails = resultTexts.map(text => text.description);
          if (fontDetails.length === 0)
            return null;
          const fontTable = fontDetails[0];
          fontDetails.shift();
          const fontJson = JSON.stringify({font:fontTable, words:fontDetails})
          console.log("Font details loaded");
          return fontJson;
        }

        async function putDetailsToDB(id, data){
          console.log("Putting font details to DB");
          const fetch = require('node-fetch');
          const URL = JSON.parse(process.env.API_CONFIG).API_URL + '/' + id;
          const response = await fetch(URL,{
            method:'PUT',
            body: data,
            headers: {
              'Content-type': 'application/json',
            },
          });
          await console.log("Font details put to DB with status: " + response.status);
          return response.json();
        }

        function lambdaTrigger(id, eventType, eventInfo){
          console.log("Trigering function for: " + eventInfo);
          const axios = require("axios");
          const eventData = {
            'type': eventType,
            'source': event["ce-source"],
            'eventtypeversion': event["ce-eventtypeversion"],
            'specversion': event["ce-specversion"],
            'id': id,
            'data': event.data,
          };
          axios({
            method: "post",
            baseURL: process.env.EVENT_URL,
            headers: {
                "Content-Type": "application/cloudevents+json"
            },
            data: eventData,
          }).then(function (response) {
            console.log("Event post to function for: " + eventInfo + " with status: " + response.status);
          })
          .catch(function (error) {
            console.error(error);
          });
        }

        try{
          // Needed to remove unwanted apostrophes from our ID
          const imgID = event.data.slice(1, -1);
          console.log("Processing image: " + imgID);

          const base64 = await getBase64(imgID);
          const fontDetails = await getFontDetails(base64);
          const { nanoid } = require("nanoid");

          let id;
          let eventInfo;

          if(fontDetails){
            await putDetailsToDB(imgID, fontDetails);

            const textEventType = "sap.kyma.custom.showcase.textdetails.processing.v1";
            eventInfo = "entity-processing";
            id = nanoid();
            console.log("Generated nano for " + eventInfo + " " + id);
            lambdaTrigger(id, textEventType, eventInfo);
          }else {
            console.log("Text array is empty");
          }

        }catch(err){
          console.error(err);
          return null;
        }
      }
    }
