apiVersion: eventing.kyma-project.io/v1alpha1
kind: Subscription
metadata:
  name: labels-handwriting-subscription
spec:
  filter:
    filters:
    - eventSource:
        property: source
        type: exact
        value: ""
      eventType:
        property: type
        type: exact
        value: sap.kyma.custom.showcase.handwriting.processing.v1
  sink: http://labels-handwriting.default.svc.cluster.local