apiVersion: eventing.kyma-project.io/v1alpha1
kind: Subscription
metadata:
  name: objects-processing-subscription
spec:
  filter:
    filters:
    - eventSource:
        property: source
        type: exact
        value: ""
      eventType:
        property: type
        type: exact
        value: sap.kyma.custom.showcase.image.uploaded.v1
  sink: http://objects-processing.default.svc.cluster.local