apiVersion: eventing.kyma-project.io/v1alpha1
kind: Subscription
metadata:
  name: text-sentiment-subscription
spec:
  filter:
    filters:
      - eventSource:
          property: source
          type: exact
          value: ""
        eventType:
          property: type
          type: exact
          value: sap.kyma.custom.showcase.textdetails.processing.v1
  sink: http://text-sentiment.default.svc.cluster.local