// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// EventHelper is an autogenerated mock type for the EventHelper type
type EventHelper struct {
	mock.Mock
}

// SendEvent provides a mock function with given fields:
func (_m *EventHelper) SendEvent() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
