apiVersion: apps/v1
kind: Deployment
metadata:
  name: showcase-redis
  labels:
    app: showcase-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: showcase-redis
  template:
    metadata:
      labels:
        app: showcase-redis
    spec:
      containers:
        - name: showcase-redis
          image: 'docker.io/redis:6.0.5'
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          args: ['--requirepass', '$(REDIS_PASSWORD)']
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kyma-showcase-secret
                  key: REDIS_PASSWORD
