// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	model "github.com/kyma-incubator/Kyma-Showcase/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// EventBus is an autogenerated mock type for the EventBus type
type EventBus struct {
	mock.Mock
}

// SendNewImage provides a mock function with given fields: id, img
func (_m *EventBus) SendNewImage(id string, img model.Image) error {
	ret := _m.Called(id, img)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, model.Image) error); ok {
		r0 = rf(id, img)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
